[project]
name = "aiosplice"
version = "0.1.0"
requires-python = ">=3.10"
dependencies = []

[tool.setuptools]
py-modules = ["aiosplice"]

[tool.uv.workspace]
members = [
    ".",
]

[tool.uv.sources]
aiosplice = { workspace = true }

[dependency-groups]
dev = [
    "aiosplice",
    "pytest>=9.1.1",
    "pytest-asyncio>=1.4.0",
]
